# Generated by Django 4.1 on 2022-08-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthTimeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_mn', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=2, null=True)),
                ('base_tm', models.TextField(blank=True, db_collation='utf8_general_ci', null=True)),
                ('usage_amt', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'month_time_usage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonthUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=7, null=True)),
                ('s', models.DecimalField(blank=True, decimal_places=0, max_digits=42, null=True)),
            ],
            options={
                'db_table': 'month_usage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PopulUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_tm', models.IntegerField()),
                ('usage_amt', models.DecimalField(blank=True, decimal_places=4, max_digits=46, null=True)),
                ('life_popul', models.FloatField(blank=True, null=True)),
                ('bus_popul', models.FloatField(blank=True, null=True)),
                ('sub_popul', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'popul_usage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RainUsage06',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_dt', models.TextField(blank=True, db_collation='utf8_general_ci', null=True)),
                ('bike_usage', models.DecimalField(blank=True, decimal_places=0, max_digits=42, null=True)),
                ('rain_amt', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rain_usage_06',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StationUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.TextField(blank=True, db_collation='utf8_general_ci', null=True)),
                ('rent_amt', models.DecimalField(blank=True, decimal_places=0, max_digits=41, null=True)),
                ('return_amt', models.DecimalField(blank=True, decimal_places=0, max_digits=41, null=True)),
            ],
            options={
                'db_table': 'station_usage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_tm', models.TextField(blank=True, db_collation='utf8_general_ci', null=True)),
                ('bikeusage', models.DecimalField(blank=True, decimal_places=4, max_digits=46, null=True)),
            ],
            options={
                'db_table': 'time_usage',
                'managed': False,
            },
        ),
    ]
